version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: clynera_mysql_container
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=laboratorio_clinico
      - MYSQL_USER=clynera_user
      - MYSQL_PASSWORD=clynera_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: