version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: clynera_db_container
    restart: unless-stopped
    environment:
      - POSTGRES_USER=clynera_user
      - POSTGRES_PASSWORD=clynera_password
      - POSTGRES_DB=clynera_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: